### ISSUE TITLE
Review approaches to locating objects of interest

### ISSUE THREAD

**Issue by ianfore** [ga4gh/TASC#22]
Suggest that TASC review of relative roles of Search and DRS bundling is needed. Current bundling use cases in the examples given below may be better addressed through the ability to identify objects of interest through queries against defined schema. Bundling as a bag of objects provides insufficient information to users.

Illustrative examples are provided in [this issue](https://github.com/ga4gh/cloud-interop-testing/issues/104) 

Some key questions for consideration:
- Should the question of how a complex object is unpacked and handled be left to tools that are specific to those complex objects? In this situation DRS should confine itself to indicating the type of the object. Use of those objects is then handled by calling upon tools that know how to work with that type. AKA - separation of concerns.
- If we support complex objects what schema mechanism could be used for representing the content of a bundle? Could SchemaBlocks or other existing standards be used?
- Is [Research Objects](https://www.researchobject.org) a suitable standard for this which GA4GH could adopt?

**Comment by uniqueg** [comment]
If I understand the problem correctly, indeed it sounds like something that RO-Crate addresses, at least with respect to linking data models to entities. In any case I think that DRS should only (optionally) reference schemas, not "unpack" entities themselves (i.e., +1 for separation of concerns, we probably don't want to overload DRS too much).

That being said, this issue is probably more fitting for [DaMaSC](https://www.ga4gh.org/product/data-model-and-schema-consensus-damasc/) at this point?

**Comment by ianfore** [comment]
Suggesting we should close this. There are two routes by which the issue can be handled:

- Schemas in Discovery mechanisms (Data Connect, Beacon) allow identification of individual files according to their attributes 
- DRS has deprecated bundling and recommended that objects consisting of multiple files are represented in some standard format which includes a manifest describing the structure. DRS deliberately didn't address what manifest format would be used.

Yes DaMaSC can potentially address the first of these. RO-Crate is a candidate in the second case.
